<a href="https://colab.research.google.com/github/JACOBABRAHAMJANE/page/blob/main/NLP_program.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install nltk


In [3]:
# WORD TOKENIZATION
import nltk # make sure to import nltk

nltk.download('punkt_tab') # Download the 'punkt_tab' resource

from nltk.tokenize import word_tokenize
text = "Natural Language Processing is fascinating!"
tokens = word_tokenize(text)
print(tokens)
text = "I am running this code in Jupyter!"
tokens = word_tokenize(text)
print(tokens)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


['Natural', 'Language', 'Processing', 'is', 'fascinating', '!']
['I', 'am', 'running', 'this', 'code', 'in', 'Jupyter', '!']


In [4]:
# STEMMING
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
words = ['running', 'runner', 'runs', 'easily', 'faster']
stemmed_words= [stemmer.stem(word) for word in words]
print(stemmed_words)
words = ['eating', 'ate', 'goes', 'ease', 'read']
stemmed_words= [stemmer.stem(word) for word in words]
print(stemmed_words)

['run', 'runner', 'run', 'easili', 'faster']
['eat', 'ate', 'goe', 'eas', 'read']


In [6]:
import nltk
nltk.download('wordnet')
# LEMMATIZATION
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
words = ['running', 'runner', 'flies', 'easily', 'better']
lemmatized_words = [lemmatizer.lemmatize(word, pos = 'v') for word in words]
print( lemmatized_words)
words = ['eating', 'ate', 'goes', 'ease', 'read']
lemmatized_words = [lemmatizer.lemmatize(word, pos = 'v') for word in words]
print( lemmatized_words)

[nltk_data] Downloading package wordnet to /root/nltk_data...


['run', 'runner', 'fly', 'easily', 'better']
['eat', 'eat', 'go', 'ease', 'read']


In [9]:
#STOP WORDS
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt')
def remove_stopwords(text):
    stop_words = set(stopwords.words('english')) # Indented this line
    words = word_tokenize(text)
    filtered_words = [word for word in words if word.lower() not in stop_words]
    return ' '.join(filtered_words)
sample_text = "This is an example sentence demonstrating the removal of stop words."
#sample_text = input()
filtered_text = remove_stopwords(sample_text)
print("Filtered Text:", filtered_text)

Filtered Text: example sentence demonstrating removal stop words .


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [18]:
#2 spel checker
!pip install pyspellchecker

In [12]:
from spellchecker import SpellChecker
def correct_spelling(text):
    spell = SpellChecker()
    words = text.split()
    corrected_words = [spell.correction(word) if spell.correction(word)
else word for word in words]
    corrected_text = " ".join(corrected_words)
    return corrected_text
text = "Ths is a smple tst for speling corection."
#text = input()
corrected_text = correct_spelling(text)
print("Original Text: ", text)
print("Corrected Text: ", corrected_text)


Original Text:  Ths is a smple tst for speling corection.
Corrected Text:  the is a simple test for spelling corrections


In [16]:
# 3WORD SEGMENTATION
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')
def segment_text(text):
    words = word_tokenize(text) # Indented this line
    return words # Indented this line
text = "Word segmentation is the process of dividing a string of written language into meaningful words."
segmented_words = segment_text(text)
print(segmented_words)

['Word', 'segmentation', 'is', 'the', 'process', 'of', 'dividing', 'a', 'string', 'of', 'written', 'language', 'into', 'meaningful', 'words', '.']


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [15]:
# SENTENCE SEGMENTATION
from nltk.tokenize import sent_tokenize
text = " Natural Language Processing is fascinating. It has many applications in AI."
sentences = sent_tokenize(text)
print(sentences)
text = " Natural Language Processing is used to develop AI Bots."
sentences = sent_tokenize(text)
print(sentences)

[' Natural Language Processing is fascinating.', 'It has many applications in AI.']
[' Natural Language Processing is used to develop AI Bots.']


In [20]:
#4
!pip install scikit-learn

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
"Natural Language Processing is exciting",
"Machine Learning is part of AI",
"AI and NLP are closely related"
]
vectorizer = CountVectorizer(ngram_range=(1, 2))
X = vectorizer.fit_transform(corpus)
feature_names = vectorizer.get_feature_names_out()
X_array = X.toarray()
print("Feature Names (N-grams):")
print(feature_names)
print("\nCount Matrix:")
print(X_array)

Feature Names (N-grams):
['ai' 'ai and' 'and' 'and nlp' 'are' 'are closely' 'closely'
 'closely related' 'exciting' 'is' 'is exciting' 'is part' 'language'
 'language processing' 'learning' 'learning is' 'machine'
 'machine learning' 'natural' 'natural language' 'nlp' 'nlp are' 'of'
 'of ai' 'part' 'part of' 'processing' 'processing is' 'related']

Count Matrix:
[[0 0 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0]
 [1 0 0 0 0 0 0 0 0 1 0 1 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0]
 [1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1]]


In [23]:
#5
!pip install nltk scikit-learn

In [24]:
#5BAG OF WORDS
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
"Natural Language Processing is exciting",
"Machine Learning is part of AI",
"AI and NLP are closely related"
]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
feature_names = vectorizer.get_feature_names_out()
X_array = X.toarray()
print("Feature Names (BoW):")
print(feature_names)
print("\nBag of Words Matrix:")
print(X_array)

Feature Names (BoW):
['ai' 'and' 'are' 'closely' 'exciting' 'is' 'language' 'learning'
 'machine' 'natural' 'nlp' 'of' 'part' 'processing' 'related']

Bag of Words Matrix:
[[0 0 0 0 1 1 1 0 0 1 0 0 0 1 0]
 [1 0 0 0 0 1 0 1 1 0 0 1 1 0 0]
 [1 1 1 1 0 0 0 0 0 0 1 0 0 0 1]]


In [27]:
# POS TAGGING
import nltk
from nltk.tokenize import word_tokenize
from nltk import pos_tag
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger_eng') # Download the correct resource
sentence = "Machine learning enables computers to learn from data."
words = word_tokenize(sentence)
pos_tags = pos_tag(words)
print("POS Tagging Result:")
print(pos_tags)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.


POS Tagging Result:
[('Machine', 'NN'), ('learning', 'VBG'), ('enables', 'NNS'), ('computers', 'NNS'), ('to', 'TO'), ('learn', 'VB'), ('from', 'IN'), ('data', 'NNS'), ('.', '.')]


In [28]:
#6
import nltk
from nltk.tokenize import MWETokenizer, word_tokenize
mwe_tokenizer = MWETokenizer([("New", "York"), ("machine", "learning"), ("artificial", "intelligence")])
text = "New York is a hub for machine learning and artificial intelligence research."
tokens = word_tokenize(text)
mwe_tokens = mwe_tokenizer.tokenize(tokens)
print("Original Tokens:", tokens)
print("Multiword Tokens:", mwe_tokens)

Original Tokens: ['New', 'York', 'is', 'a', 'hub', 'for', 'machine', 'learning', 'and', 'artificial', 'intelligence', 'research', '.']
Multiword Tokens: ['New_York', 'is', 'a', 'hub', 'for', 'machine_learning', 'and', 'artificial_intelligence', 'research', '.']


In [30]:
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
nltk.download('punkt')
nltk.download('stopwords')
def clean_text(text):
    text = text.lower()  # Indented this line
    text = re.sub(r'\W+', ' ', text)   # Indented this line
    words = word_tokenize(text)   # Indented this line
    words = [word for word in words if word not in stopwords.words('english')]   # Indented this line
    return " ".join(words) # Indented this line
sample_text = "Hello! This is an example of Natural Language Processing (NLP) cleaning."
cleaned_text = clean_text(sample_text)
print("Original Text:")
print(sample_text)
print("\nCleaned Text:")
print(cleaned_text)

Original Text:
Hello! This is an example of Natural Language Processing (NLP) cleaning.

Cleaned Text:
hello example natural language processing nlp cleaning


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [31]:
#8
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
"Natural Language Processing is exciting",
"Machine Learning is a part of AI",
"AI and NLP are closely related"
]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
feature_names = vectorizer.get_feature_names_out()
X_array = X.toarray()
print("Feature Names (TF-IDF):")
print(feature_names)
print("\nTF-IDF Matrix:")
print(X_array)

Feature Names (TF-IDF):
['ai' 'and' 'are' 'closely' 'exciting' 'is' 'language' 'learning'
 'machine' 'natural' 'nlp' 'of' 'part' 'processing' 'related']

TF-IDF Matrix:
[[0.         0.         0.         0.         0.46735098 0.35543247
  0.46735098 0.         0.         0.46735098 0.         0.
  0.         0.46735098 0.        ]
 [0.3349067  0.         0.         0.         0.         0.3349067
  0.         0.44036207 0.44036207 0.         0.         0.44036207
  0.44036207 0.         0.        ]
 [0.32200242 0.42339448 0.42339448 0.42339448 0.         0.
  0.         0.         0.         0.         0.42339448 0.
  0.         0.         0.42339448]]


In [32]:
#9
import nltk
from nltk.corpus import wordnet
nltk.download('wordnet')
def get_wordnet_info(word):
    synonyms = []
    antonyms = []
    synsets = wordnet.synsets(word)
    if not synsets:
        return f"No WordNet data found for '{word}'"
    for syn in synsets:
        synonyms.extend(syn.lemma_names())
        print(f"Definition: {syn.definition()}")
        print(f"Example: {syn.examples()}\n")
    for syn in synsets:
        for lemma in syn.lemmas():
            if lemma.antonyms():
                antonyms.append(lemma.antonyms()[0].name())
    return {
        "Synonyms": set(synonyms),
        "Antonyms": set(antonyms)
    }
word = "happy"
word_info = get_wordnet_info(word)
print("\nSynonyms:", word_info["Synonyms"])
print("Antonyms:", word_info["Antonyms"])

Definition: enjoying or showing or marked by joy or pleasure
Example: ['a happy smile', 'spent many happy days on the beach', 'a happy marriage']

Definition: marked by good fortune
Example: ['a felicitous life', 'a happy outcome']

Definition: eagerly disposed to act or to be of service
Example: ['glad to help']

Definition: well expressed and to the point
Example: ['a happy turn of phrase', 'a few well-chosen words']


Synonyms: {'felicitous', 'well-chosen', 'happy', 'glad'}
Antonyms: {'unhappy'}


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [34]:
#10
!pip install hmmlearn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 165.9/165.9 kB 2.9 MB/s eta 0:00:00


In [35]:
import numpy as np
from hmmlearn import hmm
states = ["Noun", "Verb", "Adjective"]
num_states = len(states)
observations = ["dog", "barks", "happy", "cat", "runs", "blue"]
num_observations = len(observations)
state_dict = {state: i for i, state in enumerate(states)}
obs_dict = {obs: i for i, obs in enumerate(observations)}
model = hmm.MultinomialHMM(n_components=num_states, n_iter=1000)
model.startprob_ = np.array([0.5, 0.3, 0.2])
model.transmat_ = np.array([
    [0.6, 0.3, 0.1],
    [0.2, 0.7, 0.1],
    [0.3, 0.3, 0.4]
])
model.emissionprob_ = np.array([
    [0.6, 0.2, 0.2],
    [0.1, 0.8, 0.1],
    [0.2, 0.3, 0.5]
])
train_sequences = [
    ["dog", "barks", "happy"],
    ["cat", "runs", "blue"],
    ["dog", "runs", "happy"],
]
train_data = np.array([[obs_dict[word]] for seq in train_sequences for
word in seq])
model.fit(train_data)
test_seq = ["dog", "barks", "blue"]
test_data = np.array([[obs_dict[word]] for word in test_seq])
hidden_states = model.predict(test_data)
predicted_tags = [states[state] for state in hidden_states]
print("\n Test Observations:", test_seq)
print(" Predicted POS Tags:", predicted_tags)

https://github.com/hmmlearn/hmmlearn/issues/335
https://github.com/hmmlearn/hmmlearn/issues/340



 Test Observations: ['dog', 'barks', 'blue']
 Predicted POS Tags: ['Noun', 'Verb', 'Adjective']


In [45]:
import numpy as np

states = ["Noun", "Verb", "Adjective"]
observations = ["dog", "barks", "happy"]
obs_map = {word: i for i, word in enumerate(observations)}
start_prob = np.array([0.5, 0.3, 0.2])
trans_prob = np.array([
    [0.6, 0.3, 0.1],
    [0.2, 0.7, 0.1],
    [0.3, 0.3, 0.4]
])
emission_prob = np.array([
    [0.7, 0.2, 0.1],
    [0.1, 0.8, 0.1],
    [0.2, 0.3, 0.5]
])
obs_seq = ["dog", "barks", "happy"]

def viterbi(obs_seq, states, start_prob, trans_prob, emission_prob):
    num_obs = len(obs_seq)
    num_states = len(states)
    viterbi_matrix = np.zeros((num_states, num_obs))
    backpointer = np.zeros((num_states, num_obs), dtype=int)
    for s in range(num_states):
        viterbi_matrix[s, 0] = start_prob[s] * emission_prob[s, obs_map[obs_seq[0]]]
        backpointer[s, 0] = 0
    for t in range(1, num_obs):
        for s in range(num_states):
            max_prob, prev_state = max(
                (viterbi_matrix[prev_s, t-1] * trans_prob[prev_s, s] * emission_prob[s, obs_map[obs_seq[t]]], prev_s)
                for prev_s in range(num_states)
            )
            viterbi_matrix[s, t] = max_prob
            backpointer[s, t] = prev_state
    # Corrected indentation here
    best_last_state = np.argmax(viterbi_matrix[:, -1])
    best_path = [best_last_state]
    for t in range(num_obs - 1, 0, -1):
        best_path.insert(0, backpointer[best_path[0], t])
        best_state_sequence = [states[i] for i in best_path]
    return best_state_sequence

predicted_tags = viterbi(obs_seq, states, start_prob, trans_prob, emission_prob)
print("Observations:", obs_seq)
print("Predicted POS Tags:", predicted_tags)

Observations: ['dog', 'barks', 'happy']
Predicted POS Tags: ['Noun', 'Verb', 'Verb']


In [41]:
#12
!pip install googletrans==3.1.0a0

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.1/55.1 kB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.4/133.4 kB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.0/65.0 kB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 29.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.6/53.6 kB 3.8 MB/s eta 0:00:00
  Created wheel for googletrans: filename=googletrans-3.1.0a0-py3-none-any.whl size=16352 sha256=05a01f4f0cfec6ab176b1ec6d0bc9bcbc4c3bf2de2848796a6623ebbedaa695b
  Stored in directory: /root/.cache/pip/wheels/81/f2/e0/d578821d723b473d18610ea93810e4a5402463919f07e603d9
Successfully built googletrans
  Attempting uninstall: hyperframe
    Found existing installation: hyperframe 6.1.0
    Uninstalling hyperframe

In [42]:
from googletrans import Translator
translator = Translator()
def translate_text(text, src_lang="auto", dest_lang="fr"):
    try: # Indented this line to be part of the function definition
        translated = translator.translate(text, src=src_lang, dest=dest_lang)
        return translated.text
    except Exception as e: # Indented this line to be part of the function definition
        return f"Translation Error: {str(e)}"
input_text = "Hello, how are you?"
translated_text = translate_text(input_text, src_lang="en", dest_lang="hi")
translated_text1 = translate_text(input_text, src_lang="en", dest_lang="te")
print(f"Original: {input_text}")
print(f"Translated: {translated_text}")
print(f"Translated: {translated_text1}")

Original: Hello, how are you?
Translated: नमस्ते, आप कैसे हैं?
Translated: హలో, మీరు ఎలా ఉన్నారు?
